---
- name: Update apt
  apt: update_cache=yes cache_valid_time=3600
  tags: apt

- name: Install some base packages
  apt: pkg="{{item}}" state=latest
  tags: apt
  with_items:
    - build-essential
    - libpq-dev
    - python3
    - python3-dev
    - python3-pip
    - python3-software-properties
    - python3-virtualenv
    - vim-nox
    - htop

# What else should go in here?
# vim + vim configuration for python?
